Controllers/homeController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace JoinSolutions.Website.Controllers
{
    public class homeController : BaseController
    {
      
        public ActionResult Dashboard()
        {
            return View();
        }

        //filling language section
        public ActionResult change(string languageAbbrevation)
        {
            Session["language"] = "en";
            if (languageAbbrevation != null)
            {
                Session["languge"] = languageAbbrevation;
            }
            
                
          
            return Redirect(Request.UrlReferrer.ToString());
            //return View(viewName);
        }

        //method to changing Language
        public static void changeLanguage( string session )
        {
            if (session != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(session);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(session);
            }
        }


        // GET: home
        public ActionResult index()
        {
            if (Session["language"] != null)
            {
                changeLanguage(Session["languge"].ToString());
            }
            
            return View();
        }

        ///about
        public ActionResult about()
        {
            if (Session["language"] != null)
            {
                changeLanguage(Session["languge"].ToString());
            }
            return View();
        }


        //contact
        public ActionResult contact()
        {
            if (Session["language"] != null)
            {
                changeLanguage(Session["languge"].ToString());
            }
            return View();
        }

        //contact
        public ActionResult employer()
        {
            if (Session["language"] != null)
            {
                changeLanguage(Session["languge"].ToString());
            }
            return View();
        }

        //coachingSessions
        public ActionResult coachingSessions()
        {
            if (Session["language"] != null)
            {
                changeLanguage(Session["languge"].ToString());
            }
            return View();
        }

        //contact
        public ActionResult jobSeekers()
        {
            if (Session["language"] != null)
            {
                changeLanguage(Session["languge"].ToString());
            }
            return View();
        }

        //contact
        public ActionResult recruiters()
        {
            if (Session["language"] != null)
            {
                changeLanguage(Session["languge"].ToString());
            }
            return View();
        }

        //contact
        public ActionResult coaching()
        {
            if (Session["language"] != null)
            {
                changeLanguage(Session["languge"].ToString());
            }
            return View();
        }


    }
}

Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>



    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />

    <!-- App css -->
    <link href="~/Content/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" id="bs-default-stylesheet" />
    <link href="~/Content/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-default-stylesheet" />

    <link href="~/Content/assets/css/bootstrap-dark.min.css" rel="stylesheet" type="text/css" id="bs-dark-stylesheet" disabled />
    <link href="~/Content/assets/css/app-dark.min.css" rel="stylesheet" type="text/css" id="app-dark-stylesheet" disabled />

    <!-- icons -->
    <link href="~/Content/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <script src="~/js/jquery.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/map-helper.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/swiper.min.js"></script>
    <script src="~/js/theme.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/gmaps.js"></script>
    <script src="~/js/isotope.js"></script>

    <!-- Vendor js -->
    <script src="~/Content/assets/js/vendor.min.js"></script>

    <!-- App js -->
    <script src="~/Content/assets/js/app.min.js"></script>



</body>
</html>

Views/Shared/_Layout.cshtml
@using JoinSolutions.Website.Helpers;
@using JoinSolutions.Website.Enums;
@using JoinSolutions.Website.Data;

<!DOCTYPE html>
@{
    var culture = string.IsNullOrEmpty(CultureHelper.CurrentCulture) ? CultureHelper.DefaultCulture : CultureHelper.CurrentCulture;
    var user = (JoinSolutions.Website.Data.User)Session["CurrentUser"];
    JoinDBEntities db = new JoinDBEntities();
    var userPermissions = db.UserPagePermissions.Where(o=>o.userId == user.id);
}
<html lang="@culture">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js" integrity="sha512-EanukVTZc4W9tUCLnDl069Izidg49PcNRKO1upLzKt9ajq66i+bXOtlzXcIbRhb6vVEGF6BCc8wQi5T1ztCpTQ==" crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />

    <!-- App css -->
    <link href="~/Content/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" id="bs-default-stylesheet" />

    @if (culture.ToLower() == "en" || culture.ToLower() == "en-US")
    {
        <link href="~/Content/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-default-stylesheet" />
        <link href="~/Content/style-en.css" rel="stylesheet" />
    }
    else
    {
        <link href="~/Content/assets/css/app-rtl.min.css" rel="stylesheet" type="text/css" id="app-default-stylesheet" />
        <link href="~/Content/style-ar.css" rel="stylesheet" />
    }
    <link href="~/Content/assets/css/bootstrap-dark.min.css" rel="stylesheet" type="text/css" id="bs-dark-stylesheet" disabled />
    <link href="~/Content/assets/css/app-dark.min.css" rel="stylesheet" type="text/css" id="app-dark-stylesheet" disabled />

    <!-- icons -->
    <link href="~/Content/assets/css/icons.min.css" rel="stylesheet" type="text/css" />




    <style>

        .btn a {
            color: inherit;
            text-decoration: none;
            background-color: transparent;
        }

        #sidebar-menu .menu-title {
            font-size: 16px;
        }

        .content {
            margin-top: 30px;
        }

        .navbar-custom .topnav-menu .nav-link {
            display: inline;
        }

        .navbar-custom {
            background-color: #2d3192 !important;
        }
    </style>
</head>
<body>

    <input type="hidden" id="ENLang" name="ENLang" value="EN" />
    <input type="hidden" id="ARLang" name="ARLang" value="AR" />

    <!-- Begin page -->
    <div id="wrapper">

        <!-- Topbar Start -->
        <div class="navbar-custom">
            <div class="container-fluid">
                <ul class="list-unstyled topnav-menu float-right mb-0">
                    @if (culture.ToLower() == "en" || culture.ToLower() == "en-US")
                    {
                        <li style="margin-top:30px" class="arabic-float-right setLang dropdown notification-list topbar-dropdown" data-lang="ar" id="fold"><span id="fold_p" class="nav-lang" style="color:white">AR</span></li>
                    }
                    else
                    {
                        <li style="margin-top:30px" class="arabic-float-right setLang dropdown notification-list topbar-dropdown" data-lang="en" id="fold"><span id="fold_p" class="nav-lang" style="color:white">EN</span></li>
                    }

                    <li class="dropdown notification-list topbar-dropdown">


                        <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" href="/Account/LogOut">

                            <span class="pro-user-name ml-1">
                                @Resources.dashboardCommon.logOut
                            </span>


                        </a>

                    </li>





                </ul>

                <!-- LOGO -->
                <div class="logo-box">
                    <a href="/Estimates/Index" class="logo logo-dark text-center">
                        <span class="logo-sm">
                            <img style="width:65%" src="~/images/logo.png" />
                            <!-- <span class="logo-lg-text-light">UBold</span> -->
                        </span>
                        <span class="logo-lg">
                            <img style="width:65%" src="~/images/logo.png" />
                            <!-- <span class="logo-lg-text-light">U</span> -->
                        </span>
                    </a>

                    <a href="/Estimates/Index" class="logo logo-light text-center">
                        <span class="logo-sm">
                            <img style="width:65%" src="~/images/logo.png" />
                        </span>
                        <span class="logo-lg">

                            <img style="width:65%" src="~/images/logo.png" />
                        </span>
                    </a>
                </div>

                <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
                    <li>
                        <button class="button-menu-mobile waves-effect waves-light">
                            <i class="fe-menu"></i>
                        </button>
                    </li>

                    <li>
                        <!-- Mobile menu toggle (Horizontal Layout)-->
                        <a class="navbar-toggle nav-link" data-toggle="collapse" data-target="#topnav-menu-content">
                            <div class="lines">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </a>
                        <!-- End mobile menu toggle-->
                    </li>

                </ul>

            </div>
        </div>
        <!-- end Topbar -->
        <!-- ========== Left Sidebar Start ========== -->
        <div class="left-side-menu">

            <div class="h-100" data-simplebar>



                <!--- Sidemenu -->
                <div id="sidebar-menu">

                    <ul id="side-menu">

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.ProductCategories && o.isEnabled))
                        {
                            <li>
                                <a href="/ProductCategories">
                                    <i data-feather="activity"></i>
                                    <span> @Resources.dashboardCommon.categories</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.Suppliers && o.isEnabled))
                        {
                            <li>
                                <a href="/Suppliers">
                                    <i data-feather="rss"></i>
                                    <span> @Resources.dashboardCommon.suppliers</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.Users && o.isEnabled))
                        {
                            <li>
                                <a href="/Users">
                                    <i data-feather="users"></i>
                                    <span> @Resources.dashboardCommon.Users</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.Products && o.isEnabled))
                        {
                            <li>
                                <a href="/Products">
                                    <i data-feather="briefcase"></i>
                                    <span> @Resources.dashboardCommon.Products</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.OfferTypes && o.isEnabled))
                        {
                            <li>
                                <a href="/OfferTypes">
                                    <i data-feather="map"></i>
                                    <span> @Resources.dashboardCommon.OfferTypes</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.Proposals && o.isEnabled))
                        {
                            <li>
                                <a href="/Estimates">
                                    <i data-feather="map"></i>
                                    <span> @Resources.dashboardCommon.Porposals</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.TendarStages && o.isEnabled))
                        {
                            <li>
                                <a href="/OpportunityStages">
                                    <i data-feather="map"></i>
                                    <span> @Resources.estimates.opportunityStages</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.Accounts && o.isEnabled))
                        {
                            <li>
                                <a href="/CrmAccounts">
                                    <i data-feather="map"></i>
                                    <span> @Resources.task.accounts</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.Tendars && o.isEnabled))
                        {
                            <li>
                                <a href="/Opportunities">
                                    <i data-feather="map"></i>
                                    <span> @Resources.opportunities.Opportunities</span>
                                </a>
                            </li>
                        }


                        @if (userPermissions.Any(o => o.pageId == (int)Pages.Tasks && o.isEnabled))
                        {
                            <li>
                                <a href="/Tasks">
                                    <i data-feather="map"></i>
                                    <span> @Resources.task.tasks</span>
                                </a>
                            </li>
                        }

                        @if (userPermissions.Any(o => o.pageId == (int)Pages.Reports && o.isEnabled))
                        {
                            <li>
                                <a href="#">
                                    <i data-feather="map"></i>
                                    <span> @Resources.task.reports</span>
                                </a>
                            </li>
                        }



                    </ul>

                </div>
                <!-- End Sidebar -->


            </div>
            <!-- Sidebar -left -->

        </div>
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start Page Content here -->
        <!-- ============================================================== -->

        <div class="content-page">
            <div class="content">

                <!-- Start Content-->
                <div class="container-fluid">
                    @RenderBody()

                </div> <!-- container -->

            </div> <!-- content -->
            <!-- Footer Start -->
            <!-- end Footer -->

        </div>

        <!-- ============================================================== -->
        <!-- End Page content -->
        <!-- ============================================================== -->


    </div>
    <!-- END wrapper -->
    <!-- Right Sidebar -->
    @*<script src="~/js/jquery.js"></script>
        <script src="~/js/jquery.validate.min.js"></script>
        <script src="~/js/map-helper.js"></script>*@
    @*<script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/swiper.min.js"></script>
        <script src="~/js/theme.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/gmaps.js"></script>
        <script src="~/js/isotope.js"></script>*@



    <!-- Dashboard 2 init -->
    <!-- Vendor js -->
    <script src="~/Content/assets/js/vendor.min.js"></script>

    <!-- App js -->
    <script src="~/Content/assets/js/app.min.js"></script>

    <script src="~/Scripts/App/multiLanguage.js"></script>




</body>
</html>

Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE HTML>
@using JoinSolutions.Website.Helpers;
@{
    var culture = string.IsNullOrEmpty(CultureHelper.CurrentCulture) ? CultureHelper.DefaultCulture : CultureHelper.CurrentCulture;
}

<html lang="@culture">
<head>
    <meta charset="UTF-8">
    <title>@ViewBag.Title</title>

    <meta name="keywords" content="Join Solutions" />
    <meta name="description" content="Join Solutions - Let Employer Branding Begin">
    <meta name="author" content="JoinSolutions">
    <meta name="viewport" content="width=device-width">

    <!-- Include All CSS here-->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/css/owl.carousel.css" />
    <link rel="stylesheet" type="text/css" href="~/css/owl.theme.css" />
    <link rel="stylesheet" type="text/css" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/animate.css" />
    <link rel="stylesheet" type="text/css" href="~/css/magnific-popup.css" />
    <link rel="stylesheet" type="text/css" href="~/css/settings.css" />
    <link rel="stylesheet" type="text/css" href="~/css/slick.css" />
    <link rel="stylesheet" type="text/css" href="~/css/icons.css" />
    <link rel="stylesheet" type="text/css" href="~/css/preset.css" />
    <link rel="stylesheet" type="text/css" href="~/css/theme.css" />
    <link rel="stylesheet" type="text/css" href="~/css/responsive.css" />
    <link rel="stylesheet" type="text/css" href="~/css/presets/color1.css" id="colorChange" />
    <!-- End Include All CSS -->
    <!-- Favicon Icon -->
    <link rel="icon" type="image/png" href="~/images/favicon.png">





</head>
<body>
    <input type="hidden" id="ENLang" name="ENLang" value="EN" />
    <input type="hidden" id="ARLang" name="ARLang" value="AR" />
    <!-- Preloading -->
    <div class="preloader text-center">
        <div class="la-ball-circus la-2x">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- Preloading -->
    <!-- Header 01 -->
    <header class="header_01" id="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2 col-sm-3 col-md-3">
                    <div class="logo">
                        <a href="/home/index"><img src="~/images/logo.png" alt="" /></a>
                    </div>
                </div>
                <div class="col-lg-9 col-sm-7 col-md-7">
                    @{
                        string currentView = ((RazorView)ViewContext.View).ViewPath;
                    }
                    <nav class="mainmenu text-center">
                        <ul>
                            <li>@Html.ActionLink(Resources.menu.employer, "employer", "home")</li>
                            <li>@Html.ActionLink(Resources.menu.jobseekers, "jobSeekers", "home")</li>
                            <li>@Html.ActionLink(Resources.menu.recruiters, "recruiters", "home")</li>
                            <li>@Html.ActionLink(Resources.menu.coaching, "coaching", "home")</li>
                            @*<li>@Html.ActionLink("En", "change", "home", new { languageAbbrevation = "en" }, null)</li>
                                <li>@Html.ActionLink("العربية", "change", "home", new { languageAbbrevation = "Ar" }, null)</li>*@
                            @if (culture.ToLower() == "en" || culture.ToLower() == "en-US")
                            {
                                <li class="arabic-float-right setLang" data-lang="ar" id="fold"><span id="fold_p" class="nav-lang" style="color:white">AR</span></li>
                            }
                            else
                            {
                                <li class="arabic-float-right setLang" data-lang="en" id="fold"><span id="fold_p" class="nav-lang" style="color:white">EN</span></li>
                            }
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-1 col-sm-2 col-md-2">
                    <div class="navigator text-right">
                        @*<a class="search searchToggler" href="javascript:void(0);"><i class="mei-magnifying-glass"></i></a>*@
                        <a href="javascript:void(0);" class="menu mobilemenu hidden-sm hidden-md hidden-lg hidden-xs"><img class="color-bars" src="~/images/color-bars.png" /></a>
                        <a id="open-overlay-nav" class="menu hamburger" href="javascript:void(0);"><img class="color-bars" src="~/images/color-bars.png" /></a>

                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header 01 -->
    <!-- Search From -->
    <div class="searchFixed popupBG">
        <div class="container-fluid">
            <a href="" id="sfCloser" class="sfCloser"></a>
            <div class="searchForms">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <form method="post" action="#">
                                <input type="text" name="s" class="searchField" placeholder="@Resources.menu.search" />
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search From -->
    <!-- PopUP Menu -->
    <div class="popup popup__menu">
        <a href="" id="close-popup" class="close-popup"></a>
        <div class="container mobileContainer">
            <div class="row">
                <div class="col-lg-12 text-left">
                    <div class="logo2">
                        <a href="/home/index"><img src="~/images/logo.png" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="popup-inner">
                        <div class="dl-menu__wrap dl-menuwrapper">
                            <ul class="dl-menu dl-menuopen">
                                @*<li>@Html.ActionLink(Resources.menu.about, "about", "home")</li>*@
                                <li>@Html.ActionLink(Resources.menu.employer, "employer", "home")</li>
                                <li>@Html.ActionLink(Resources.menu.jobseekers, "jobSeekers", "home")</li>
                                <li>@Html.ActionLink(Resources.menu.recruiters, "recruiters", "home")</li>
                                <li>@Html.ActionLink(Resources.menu.coaching, "coaching", "home")</li>
                                <li>@Html.ActionLink(Resources.menu.contact, "contact", "home")</li>
                                <li>@Html.ActionLink("En", "change", "home", new { languageAbbrevation = "en" }, null)</li>
                                <li>@Html.ActionLink("عربي", "change", "home", new { languageAbbrevation = "Ar" }, null)</li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-sm-6 col-xs-12 text-left">
                    <ul class="footer__contacts text-left">
                        <li>@Resources.contact.phone</li>
                        <li>@Resources.contact.mail</li>
                        <li>@Resources.contact.address</li>
                    </ul>
                </div>
                <div class="col-lg-6 col-sm-6 col-xs-12 col-xs-12">
                    <div class="popUp_social text-right">
                        <ul>
                            <li><a href="#"><i class="fa fa-twitter"></i>@Resources.socialLinks.Twitter</a></li>
                            <li><a href="#"><i class="fa fa-facebook-square"></i>@Resources.socialLinks.Facebook</a></li>
                            <li><a href="#"><i class="fa fa-youtube-play"></i>@Resources.socialLinks.YouTube</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- PopUP Menu -->



    @RenderBody()


    <!-- Footer Section -->
    <footer class="footer_1">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6 col-md-5">
                    <aside class="widget aboutwidget">
                        <a href="/home/index"><img src="~/images/logo.png" alt=""></a>
                        <p>
                            @Resources.contact.description
                        </p>
                    </aside>
                </div>
                <div class="col-lg-4 col-sm-4 col-md-4">
                    <aside class="widget contact_widgets">
                        <h3 class="widget_title">@Resources.contact.contactUs</h3>
                        <p>
                            @Resources.contact.address <br>

                        </p>
                        <p>@Resources.contact.phone</p>
                        <p><a href="#">@Resources.contact.mail</a></p>
                    </aside>
                </div>
                <div class="col-lg-3 col-sm-2 col-md-3">
                    <aside class="widget social_widget">
                        <h3 class="widget_title">@Resources.socialLinks.social</h3>
                        <ul>
                            <li><a href="#"><i class="fa fa-twitter"></i>@Resources.socialLinks.Twitter</a></li>
                            <li><a href="#"><i class="fa fa-facebook-square"></i>@Resources.socialLinks.Facebook</a></li>
                            <li><a href="#"><i class="fa fa-youtube-play"></i>@Resources.socialLinks.YouTube</a></li>
                        </ul>
                    </aside>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 text-center">
                    <div class="copyright">
                        @Resources.about.copyRightSection1 <a href="/home/index">@Resources.about.copyRightSection2 </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section -->
    <!-- Bact To To -->
    <a id="backToTop" href="#" class=""><i class="fa fa-angle-double-up"></i></a>
    <!-- Bact To To -->
    <!-- Include All JS -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/modernizr.custom.js"></script>
    <script src="~/js/gmaps.js"></script>
    <script src="https://maps.google.com/maps/api/js?key=AIzaSyDTPlX-43R1TpcQUyWjFgiSfL_BiGxslZU"></script>
    <script src="~/js/jquery.themepunch.revolution.min.js"></script>
    <script src="~/js/jquery.themepunch.tools.min.js"></script>
    <!-- Rev slider Add on Start -->
    <script src="~/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="~/js/extensions/revolution.extension.carousel.min.js"></script>
    <script src="~/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="~/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="~/js/extensions/revolution.extension.parallax.min.js"></script>
    <script src="~/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="~/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="~/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="~/js/extensions/revolution.extension.video.min.js"></script>
    <!-- Rev slider Add on End -->
    <script src="~/js/dlmenu.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script src="~/js/mixer.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/owl.carousel.js"></script>
    <script src="~/js/slick.js"></script>
    <script src="~/js/jquery.appear.js"></script>
    <script src="~/js/theme.js"></script>
    <!-- Include All JS -->
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js" integrity="sha512-EanukVTZc4W9tUCLnDl069Izidg49PcNRKO1upLzKt9ajq66i+bXOtlzXcIbRhb6vVEGF6BCc8wQi5T1ztCpTQ==" crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@


    <script src="~/Scripts/App/multiLanguage.js"></script>


</body>
</html>