Controllers/EstimateProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JoinSolutions.Website.Data;
using JoinSolutions.Website.Filters;

namespace JoinSolutions.Website.Controllers
{
    [SessionExpireFilter]
    public class EstimateProductsController : BaseController
    {
        private JoinDBEntities db = new JoinDBEntities();

        // GET: EstimateProducts
        public ActionResult Index()
        {
            var estimateProducts = db.EstimateProducts.OrderByDescending(o => o.id).Include(e => e.Product);
            return View(estimateProducts.ToList());
        }

        // GET: EstimateProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstimateProduct estimateProduct = db.EstimateProducts.Find(id);
            if (estimateProduct == null)
            {
                return HttpNotFound();
            }
            return View(estimateProduct);
        }

        // GET: EstimateProducts/Create
        public ActionResult Create()
        {
            ViewBag.productId = new SelectList(db.Products, "id", "productSKU");
            return View();
        }

        // POST: EstimateProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(EstimateProduct estimateProduct)
        {
            if (ModelState.IsValid)
            {
                db.EstimateProducts.Add(estimateProduct);
                db.SaveChanges();
            }

            ViewBag.productId = new SelectList(db.Products, "id", "productSKU", estimateProduct.productId);
            return RedirectToAction("Edit", "Estimates", new { id = estimateProduct.estimateId });
        }

        // GET: EstimateProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstimateProduct estimateProduct = db.EstimateProducts.Find(id);
            if (estimateProduct == null)
            {
                return HttpNotFound();
            }
            ViewBag.productId = new SelectList(db.Products, "id", "productSKU", estimateProduct.productId);
            return View(estimateProduct);
        }

        public ActionResult EditProduct(int? id = 0)
        {
            if (id == 0)
            {
                return PartialView("~/Views/EstimateProducts/_Edit.cshtml", new EstimateProduct() { 
                priceInUSD = 1,
                priceLi = 1,
                profit = 1,
                qty = 1,
                vat = 15,
                periodByMonths = 12
                });
            }
            EstimateProduct estimateProduct = db.EstimateProducts.Find(id);
            if (estimateProduct == null)
            {
                return HttpNotFound();
            }
            estimateProduct.Estimate = db.Estimates.Find(estimateProduct.estimateId);
            estimateProduct.Estimate.EstimateProducts = null;
            ViewBag.productId = new SelectList(db.Products, "id", "productSKU", id);
            return PartialView("~/Views/EstimateProducts/_Edit.cshtml", estimateProduct);
        }

        // POST: EstimateProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EstimateProduct estimateProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estimateProduct).State = EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.productId = new SelectList(db.Products, "id", "productSKU", estimateProduct.productId);
            return RedirectToAction("Edit", "Estimates", new { id = estimateProduct.estimateId });
        }

        // GET: EstimateProducts/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    EstimateProduct estimateProduct = db.EstimateProducts.Find(id);
        //    if (estimateProduct == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(estimateProduct);
        //}

        // POST: EstimateProducts/Delete/5
        [ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            EstimateProduct estimateProduct = db.EstimateProducts.Find(id);
            db.EstimateProducts.Remove(estimateProduct);
            db.SaveChanges();
            // return RedirectToAction("Index");
            return RedirectToAction("Edit", "Estimates", new { id = estimateProduct.estimateId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/EstimateProducts/Create.cshtml
@model JoinSolutions.Website.Data.EstimateProduct

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.estimateId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estimateId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estimateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productId, "productId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("productId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.productId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priceLi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.priceLi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.priceLi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priceInUSD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.priceInUSD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.priceInUSD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Resources.estimates.BackToEstimates, "Index")
</div>

Views/EstimateProducts/Delete.cshtml
@model JoinSolutions.Website.Data.EstimateProduct

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this?</h3>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.estimateId)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.estimateId)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.qty)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.qty)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.vat)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.vat)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.priceLi)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.priceLi)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.priceInUSD)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.priceInUSD)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.profit)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.profit)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Product.productSKU)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Product.productSKU)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            @Html.ActionLink(Resources.estimates.BackToEstimates, "Index", null, null, new { @class = "btn btn-info" })
                        </div>
                    }
                </div>

                <!-- end .table-responsive-->
            </div> <!-- end card-body -->
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>

Views/EstimateProducts/Details.cshtml
@model JoinSolutions.Website.Data.EstimateProduct

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">



                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.estimateId)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.estimateId)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.qty)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.qty)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.vat)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.vat)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.priceLi)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.priceLi)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.priceInUSD)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.priceInUSD)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.profit)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.profit)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Product.productSKU)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Product.productSKU)
                        </dd>

                    </dl>
                </div>
                <p>
                    @Html.ActionLink(Resources.estimates.EditEstimate, "Edit", new { id = Model.id }, new { @class = "btn btn-primary" })
                    @Html.ActionLink(Resources.estimates.BackToEstimates, "Index", null, null, new { @class = "btn btn-info" })
                </p>

                <!-- end .table-responsive-->
            </div> <!-- end card-body -->
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>

Views/EstimateProducts/Edit.cshtml
@model JoinSolutions.Website.Data.EstimateProduct

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EstimateProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.estimateId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estimateId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estimateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productId, "productId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("productId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.productId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priceLi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.priceLi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.priceLi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priceInUSD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.priceInUSD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.priceInUSD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Resources.estimates.BackToEstimates, "Index")
</div>

Views/EstimateProducts/Index.cshtml
@model IEnumerable<JoinSolutions.Website.Data.EstimateProduct>

<div style="margin-top:30px">
    <button type="button" class="btn btn-primary" onclick="openCreateModal()">@Resources.estimates.AddNewProduct</button>
</div>


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body" style="padding-left:0px;padding-right:0px">


                <table class="table table-striped">
                    <tr>
                        @*<th>
                                @Html.DisplayNameFor(model => model.estimateId)
                            </th>*@
                        <th>
                            @Resources.estimates.productNameEn
                        </th>
                        <th>
                            @Resources.estimates.periodByMonths
                        </th>
                        <th>
                            @Resources.estimates.qty
                        </th>
                        <th>
                            @Resources.estimates.CostPrice
                        </th>
                        <th>
                            @Resources.estimates.TotalCost
                        </th>
                        <th>
                            @Resources.estimates.vat
                        </th>
                        <th>
                            @Resources.estimates.profit
                        </th>
                        <th>
                            @Resources.estimates.priceInUSD
                        </th>
                        <th>
                            @Resources.estimates.PriceInSAR
                        </th>
                        <th>
                            @Resources.estimates.TotalInUSD
                        </th>
                        <th>
                            @Resources.estimates.TotalInSAR
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        var priceLiTotal = item.priceLi * item.qty;
                        var vatPrice = ((item.vat / 100) * (((double)item.Estimate.currencyRate * item.priceLi) + ((item.profit / 100) * (double)item.Estimate.currencyRate * item.priceLi)));
                        var profitPrice = item.priceLi * (double)item.Estimate.currencyRate * (item.profit / 100);
                        var priceInSAR = (item.priceInUSD) * (float)item.Estimate.currencyRate;
                        var totalInUSD = ((item.priceInUSD + vatPrice) * item.qty);
                        var totalInSAR = ((priceInSAR + vatPrice) * item.qty);

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Product.productSKU)
                            </td>
                            <td>
                                @item.periodByMonths
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.qty)
                            </td>
                            <td>
                                @*@Html.DisplayFor(modelItem => item.priceLi)*@
                                @String.Format("{0:n}", item.priceLi)
                            </td>
                            <td>
                                @*@priceLiTotal.ToString("#.000")*@
                                @String.Format("{0:n}", priceLiTotal)
                            </td>
                            <td>
                                @*@((item.vat/100) * (((double)item.Estimate.currencyRate * item.priceLi ) + ((item.profit / 100) * (double)item.Estimate.currencyRate * item.priceLi)) )*@
                                @String.Format("{0:n}", ((item.vat / 100) * (((double)item.Estimate.currencyRate * item.priceLi) + ((item.profit / 100) * (double)item.Estimate.currencyRate * item.priceLi))))
                            </td>
                            <td>
                                @*@((item.profit / 100) * (double)item.Estimate.currencyRate * item.priceLi )*@
                                @String.Format("{0:n}", ((item.profit / 100) * (double)item.Estimate.currencyRate * item.priceLi))

                            </td>
                            <td>
                                @*@item.priceInUSD*@
                                @String.Format("{0:n}", item.priceInUSD)
                            </td>
                            <td>
                                @*@priceInSAR.ToString("#.000")*@
                                @String.Format("{0:n}", priceInSAR)
                            </td>

                            <td>
                                @*@totalInUSD.ToString("#.000")*@
                                @String.Format("{0:n}", totalInUSD)
                            </td>
                            <td>
                                @*@totalInSAR.ToString("#.000")*@
                                @String.Format("{0:n}", totalInSAR)
                            </td>
                            <td>
                                @*@Html.ActionLink("Edit", "Edit", new { id = item.id }) |*@
                                <a href="javascript:void(0)" onclick="openModal(@(item.id ))">@Resources.estimates.Edit</a>
                                @*@Html.ActionLink("Details", "Details", new { id = item.id }) |*@
                                @Html.ActionLink(Resources.estimates.Delete, "Delete", "EstimateProducts", new { id = item.id }, null)
                            </td>
                        </tr>
                    }

                </table>

                <!-- end .table-responsive-->
            </div> <!-- end card-body -->
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>


<div id="standard-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="standard-modalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="standard-modalLabel">@Resources.estimates.addEditProduct</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">

                <div id="divProductDetails">
                    @Html.Partial("~/Views/EstimateProducts/_Create.cshtml", new JoinSolutions.Website.Data.EstimateProduct()
               {
                   priceInUSD = (1 * 0.15 * 0.01),
                   priceLi = 1,
                   profit = 1,
                   qty = 1,
                   vat = 15,
                   periodByMonths = 12,
                   Estimate = new JoinSolutions.Website.Data.Estimate() { currencyRate = (decimal)3.75 }
               })
                </div>

            </div>
            @*<div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>*@
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<input id="formType" name="formType" value="Add" hidden />

@*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js" integrity="sha512-EanukVTZc4W9tUCLnDl069Izidg49PcNRKO1upLzKt9ajq66i+bXOtlzXcIbRhb6vVEGF6BCc8wQi5T1ztCpTQ==" crossorigin="anonymous"></script>
<script src="~/Scripts/bootstrap.min.js"></script>*@

<script type="text/javascript">

    function openModal(productId) {
        $('#standard-modal').modal('show');
        document.getElementById("formType").value = "Edit";
        $.ajax({
            url: "/EstimateProducts/EditProduct",
            type: "post",
            data: { "id": productId },
            dataType: "html",
            async: false,
            success: function (data) {

                debugger;
                $("#divProductDetails").replaceWith(data);

                //open modal
                //$('#standard-modal').modal('show');

                //$("#standard-modal").modal({ show: true });
            }
        });


    }

    function ClearEstimateProductForm() {
        $("#qty").val(1);
        $("#vat").val(15);
        $("#priceLi").val(1);
        $("#priceInUSD").val(1);
        $("#profit").val(1);
        $("#profitPrice").val(0.01);
        $("#vatPrice").val(0.15);
        $("#priceInSAR").val(3.79);
    }

    function openCreateModal() {
        ClearEstimateProductForm();
        document.getElementById("formType").value = "Add";
        $('#standard-modal').modal('show');
    }

</script>