Controllers/OpportunitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JoinSolutions.Website.Data;
using JoinSolutions.Website.Enums;
using JoinSolutions.Website.Filters;
using JoinSolutions.Website.Helpers;
using JoinSolutions.Website.Models;

namespace JoinSolutions.Website.Controllers
{
    [SessionExpireFilter]
    public class OpportunitiesController : BaseController
    {
        private JoinDBEntities db = new JoinDBEntities();

        // GET: Opportunities
        public ActionResult Index()
        {
            var opportunities = db.Opportunities.Include(o => o.OpportunityStage).Include(o => o.User).Include(o => o.User1);
            return View(opportunities.ToList());
        }

        // GET: Opportunities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opportunity opportunity = db.Opportunities.Find(id);
            if (opportunity == null)
            {
                return HttpNotFound();
            }
            return View(opportunity);
        }

        // GET: Opportunities/Create
        public ActionResult Create(int? accountId)
        {
            ViewBag.accountId = new SelectList(db.Accounts, "accountId", "accountName", accountId);
            ViewBag.opportunityStageId = new SelectList(db.OpportunityStages, "opportunityStageId", "opportunityStageName");
            ViewBag.assignedToId = new SelectList(db.Users.Where(o => o.UserPagePermissions.Any(oo => oo.pageId == (int)Pages.Tasks)), "id", "username");
            ViewBag.createdById = new SelectList(db.Users, "id", "username");
            return View();
        }

        // POST: Opportunities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OpportunityModel opportunity)
        {
            if (ModelState.IsValid)
            {
                var opportunityEntity = new Opportunity()
                {
                    opportunityStageId = opportunity.opportunityStageId,
                    assignedToId = opportunity.assignedToId,
                    opportunityDescription = opportunity.opportunityDescription,
                    opportunityEnded = opportunity.opportunityEnded,
                    opportunityId = opportunity.opportunityId,
                    opportunityName = opportunity.opportunityName,
                    tenderPapersPrice = opportunity.tenderPapersPrice,
                    tenderCost = opportunity.tenderCost,
                    accountId = Convert.ToInt32(Session["accountId"]) == 0 ? (int?)null : Convert.ToInt32(Session["accountId"])
                };
                opportunityEntity.createdDate = LocalDateTime.GetDateTimeNow();
                opportunityEntity.createdById = ((User)Session["CurrentUser"]).id;
                db.Opportunities.Add(opportunityEntity);
                db.SaveChanges();
                return RedirectToAction("Create", "Estimates",new { tenderId = opportunityEntity.opportunityId});
            }

            ViewBag.opportunityStageId = new SelectList(db.OpportunityStages, "opportunityStageId", "opportunityStageName", opportunity.opportunityStageId);
            ViewBag.assignedToId = new SelectList(db.Users.Where(o => o.UserPagePermissions.Any(oo => oo.pageId == (int)Pages.Tasks)), "id", "username", opportunity.assignedToId);
            ViewBag.createdById = new SelectList(db.Users, "id", "username", opportunity.createdById);
            ViewBag.accountId = new SelectList(db.Accounts, "accountId", "accountName", opportunity.accountId);

            return View(opportunity);
        }

        // GET: Opportunities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opportunity opportunity = db.Opportunities.Find(id);
            if (opportunity == null)
            {
                return HttpNotFound();
            }
            ViewBag.opportunityStageId = new SelectList(db.OpportunityStages, "opportunityStageId", "opportunityStageName", opportunity.opportunityStageId);
            ViewBag.assignedToId = new SelectList(db.Users.Where(o => o.UserPagePermissions.Any(oo => oo.pageId == (int)Pages.Tasks)), "id", "username", opportunity.assignedToId);
            ViewBag.createdById = new SelectList(db.Users, "id", "username", opportunity.createdById);
            ViewBag.accountId = new SelectList(db.Accounts, "accountId", "accountName", opportunity.accountId);

            var opportunityModel = new OpportunityModel()
            {
                opportunityStageId = opportunity.opportunityStageId,
                assignedToId = opportunity.assignedToId,
                createdById = opportunity.createdById,
                createdDate = opportunity.createdDate,
                opportunityDescription = opportunity.opportunityDescription,
                opportunityEnded = opportunity.opportunityEnded,
                opportunityId = opportunity.opportunityId,
                opportunityName = opportunity.opportunityName,
                tenderCost = (double)opportunity.tenderCost,
                tenderPapersPrice = (double)opportunity.tenderPapersPrice,
                accountId = opportunity.accountId,
                Estimate = db.Estimates.FirstOrDefault(o=>o.tenderId == opportunity.opportunityId)

            };

            return View(opportunityModel);
        }

        // POST: Opportunities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OpportunityModel opportunity)
        {
            if (ModelState.IsValid)
            {
                var opportunityEntity = new Opportunity()
                {
                    opportunityStageId = opportunity.opportunityStageId,
                    assignedToId = opportunity.assignedToId,
                    createdById = opportunity.createdById,
                    createdDate = opportunity.createdDate,
                    opportunityDescription = opportunity.opportunityDescription,
                    opportunityEnded = opportunity.opportunityEnded,
                    opportunityId = opportunity.opportunityId,
                    opportunityName = opportunity.opportunityName,
                    tenderCost = opportunity.tenderCost,
                    tenderPapersPrice = opportunity.tenderPapersPrice,
                    accountId = opportunity.accountId
                };
                db.Entry(opportunityEntity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = opportunityEntity.opportunityId });
            }
            ViewBag.opportunityStageId = new SelectList(db.OpportunityStages, "opportunityStageId", "opportunityStageName", opportunity.opportunityStageId);
            ViewBag.assignedToId = new SelectList(db.Users.Where(o => o.UserPagePermissions.Any(oo => oo.pageId == (int)Pages.Tasks)), "id", "username", opportunity.assignedToId);
            ViewBag.createdById = new SelectList(db.Users, "id", "username", opportunity.createdById);
            ViewBag.accountId = new SelectList(db.Accounts, "accountId", "accountName", opportunity.accountId);

            return View(opportunity);
        }

        // GET: Opportunities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opportunity opportunity = db.Opportunities.Find(id);
            if (opportunity == null)
            {
                return HttpNotFound();
            }
            return View(opportunity);
        }

        // POST: Opportunities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Opportunity opportunity = db.Opportunities.Find(id);
            db.Opportunities.Remove(opportunity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Opportunities/Create.cshtml
@model JoinSolutions.Website.Models.OpportunityModel

@{
    ViewBag.Title = @Resources.opportunities.CreateOpportunity;
}

<ol class="topWiz">
    <li class="wizLi">@Resources.task.createNewAccount</li>
    <li class="wizLi current">@Resources.opportunities.CreateOpportunity</li>
    <li class="wizLi">@Resources.estimates.CreateNew</li>
</ol>

<h2>@Resources.opportunities.CreateOpportunity</h2>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal row">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group col-md-6">
                        @Html.Label(@Resources.opportunities.opportunityName, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.EditorFor(model => model.opportunityName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.opportunityName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.accountId, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.DropDownList("accountId", null, htmlAttributes: new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(model => model.accountId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.opportunityStageId, Resources.opportunities.opportunityStageName, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.DropDownListFor(model => model.opportunityStageId, null, Resources.opportunities.Select, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.opportunityStageId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.assignedToId, Resources.opportunities.assignedUser, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.DropDownListFor(model => model.assignedToId, null, Resources.opportunities.Select, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.assignedToId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.Label(@Resources.opportunities.opportunityEnded, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.TextBoxFor(model => model.opportunityEnded, new { @class = "form-control", @type = "date" })
                            @Html.ValidationMessageFor(model => model.opportunityEnded, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.tenderPapersPrice, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.TextBoxFor(model => model.tenderPapersPrice, new { @class = "form-control", @type = "number", @min = 0 })
                            @Html.ValidationMessageFor(model => model.tenderPapersPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.tenderCost, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.TextBoxFor(model => model.tenderCost, new { @class = "form-control", @type = "number", @min = 0 })
                            @Html.ValidationMessageFor(model => model.tenderCost, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.Label(@Resources.opportunities.opportunityDescription, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.TextAreaFor(model => model.opportunityDescription, new { @class = "form-control", @rows = 6 })
                            @Html.ValidationMessageFor(model => model.opportunityDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-12">

                        <input type="submit" value="@Resources.opportunities.Create" class="btn btn-primary" />

                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</div>



<div>
    @Html.ActionLink(@Resources.opportunities.BackToOpportunities, "Index", null, null, new { @class = "btn btn-info" })
</div>

Views/Opportunities/Delete.cshtml
@model JoinSolutions.Website.Data.Opportunity

@{
    ViewBag.Title = @Resources.opportunities.DeleteOpportunity;
}

    <h2>@Resources.opportunities.DeleteOpportunity</h2>

    <h3>@Resources.dashboardCommon.Are_you_sure_you_want_to_delete_this_</h3>
<div>
    <h4>@Resources.opportunities.Opportunity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Resources.opportunities.opportunityName
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opportunityName)
        </dd>

        <dt>
            @Resources.opportunities.opportunityEnded
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opportunityEnded)
        </dd>

        <dt>
            @Resources.opportunities.opportunityStageName
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityStage.opportunityStageName)
        </dd>

        <dt>
            @Resources.opportunities.assignedUser
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="@Resources.opportunities.Delete" class="btn btn-danger"  /> |
            @Html.ActionLink(@Resources.opportunities.BackToOpportunities, "Index", null, null, new { @class = "btn btn-info" })
        </div>
    }
</div>

Views/Opportunities/Edit.cshtml
@model JoinSolutions.Website.Models.OpportunityModel

@{
    ViewBag.Title = Resources.opportunities.EditOpportunity;
}

<h2>@Resources.opportunities.EditOpportunity</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal row">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.opportunityId)
    @Html.HiddenFor(model => model.createdDate)
    @Html.HiddenFor(model => model.createdById)

    <div class="form-group col-md-6">
        @Html.Label(@Resources.opportunities.opportunityName, htmlAttributes: new { @class = "control-label " })
        <div class="">
            @Html.EditorFor(model => model.opportunityName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.opportunityName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.accountId, htmlAttributes: new { @class = "control-label " })
        <div class="">
            @Html.DropDownList("accountId", null, htmlAttributes: new { @class = "form-control", @required = "required" })
            @Html.ValidationMessageFor(model => model.accountId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group col-md-6">
        @Html.LabelFor(model => model.opportunityStageId, Resources.opportunities.opportunityStageName, htmlAttributes: new { @class = "control-label " })
        <div class="">
            @Html.DropDownList("opportunityStageId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.opportunityStageId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-6">
        @Html.LabelFor(model => model.assignedToId, Resources.opportunities.assignedUser, htmlAttributes: new { @class = "control-label " })
        <div class="">
            @Html.DropDownList("assignedToId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.assignedToId, "", new { @class = "text-danger" })
        </div>
    </div>





    <div class="form-group col-md-6">
        @Html.Label(@Resources.opportunities.opportunityEnded, htmlAttributes: new { @class = "control-label " })
        <div class="">
            @Html.TextBoxFor(model => model.opportunityEnded, Model.opportunityEnded.ToString("yyyy-MM-dd"), new { @class = "form-control", @type = "date" })
            @Html.ValidationMessageFor(model => model.opportunityEnded, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-6">
        @Html.LabelFor(model => model.tenderCost, htmlAttributes: new { @class = "control-label " })
        <div class="">
            @Html.TextBoxFor(model => model.tenderCost, new { @class = "form-control", @type = "number", @min = 0 })
            @Html.ValidationMessageFor(model => model.tenderCost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-6">
        @Html.LabelFor(model => model.tenderPapersPrice, htmlAttributes: new { @class = "control-label " })
        <div class="">
            @Html.TextBoxFor(model => model.tenderPapersPrice, new { @class = "form-control", @type = "number", @min = 0 })
            @Html.ValidationMessageFor(model => model.tenderPapersPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-6">
        @Html.Label(@Resources.opportunities.opportunityDescription, htmlAttributes: new { @class = "control-label " })
        <div class="">
            @Html.TextAreaFor(model => model.opportunityDescription, new { @class = "form-control", @rows = 6 })
            @Html.ValidationMessageFor(model => model.opportunityDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-12">

        <input type="submit" value="@Resources.opportunities.Save" class="btn btn-primary" />
        @if (Model.Estimate == null)
        {
            <a style="margin-left:70px" href="/Estimates/Create?tenderId=@Model.opportunityId" class="btn btn-primary">@Resources.task.addNewOffer</a>
        }
        else
        {
            <a style="margin-left:70px" href="/Estimates/Edit?id=@Model.Estimate.id" class="btn btn-primary">@Resources.estimates.ShowEstimate</a>
        }
    </div>


</div>
}

<div>
    @Html.ActionLink(Resources.estimates.BackToEstimates, "Index", null, null, new { @class = "btn btn-info" })
</div>

Views/Opportunities/Index.cshtml
@model IEnumerable<JoinSolutions.Website.Data.Opportunity>
@using JoinSolutions.Website.Helpers;
@{
    ViewBag.Title = @Resources.opportunities.Opportunities;
    var culture = string.IsNullOrEmpty(CultureHelper.CurrentCulture) ? CultureHelper.DefaultCulture : CultureHelper.CurrentCulture;

}

<h2>@Resources.opportunities.Opportunities</h2>

<p>
    @Html.ActionLink(@Resources.opportunities.CreateOpportunity, "Create", "Opportunities", null, new { @class = "btn btn-primary" })
</p>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <table class="table table-striped">
                    <tr>
                        <th>
                            @Resources.opportunities.opportunityName
                        </th>
                        <th>
                            @Resources.opportunities.opportunityEnded
                        </th>
                        <th>
                            @Resources.opportunities.opportunityStageName
                        </th>
                        <th>
                            @Resources.opportunities.assignedUser
                        </th>
                        <th>@Resources.opportunities.CountDown</th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.opportunityName)
                            </td>
                            <td>
                                @item.opportunityEnded.ToShortDateString()
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OpportunityStage.opportunityStageName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.username)
                            </td>
                            <td><p style="color:red" id="counter@(item.opportunityId)"></p></td>
                            <td>
                                <a href="/Opportunities/Edit?id=@item.opportunityId">@Resources.opportunities.Edit</a>
                                @if (item.Estimates.Count() == 0)
                                {
                                    <a href="/Opportunities/Delete?id=@item.opportunityId">@Resources.opportunities.Delete</a>
                                }
                                @*@Html.ActionLink(, "Edit", "Opportunities", new { id = item.opportunityId }) |
                                    @Html.ActionLink(@Resources.opportunities.Delete, "Delete", "Opportunities", new { id = item.opportunityId })*@
                            </td>
                        </tr>
                    }

                </table>
                <!-- end .table-responsive-->
            </div> <!-- end card-body -->
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>

<script>

    $(document).ready(function () {

        @foreach (var trender in Model)
        {
        <text>
           // Set the date we're counting down to
           CalcTime("@trender.opportunityId", "@trender.opportunityEnded")
        </text>
        }

    });

    function CalcTime(opportunityId, opportunityEnded) {

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get today's date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = new Date(opportunityEnded) - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // loop through all elements having class name ".my-class"
            @if (culture.ToLower() == "en" || culture.ToLower() == "en-US")
            {
                <text>
                document.getElementById("counter" + opportunityId).innerHTML = days + "d : " + hours + "h : "
                + minutes + "m :" + seconds + "s ";
                </text>
            }
            else
            {
                <text>
                document.getElementById("counter" + opportunityId).innerHTML = days + " يوم : " + hours + " ساعة : "
                + minutes + " دقيقة :" + seconds + " ثانية ";
                </text>
            }

            // Output the result in an element with id="demo"


            // If the count down is over, write some text
            if (distance < 0) {
                clearInterval(x);
                 @if (culture.ToLower() == "en" || culture.ToLower() == "en-US")
                 {
                   <text>
                   document.querySelector("#counter" + opportunityId).innerHTML = "EXPIRED";
                   </text>
                 }
                 else
                 {
                  <text>
                  document.querySelector("#counter" + opportunityId).innerHTML = "منتهى";
                  </text>
                 }
                 }
            }, 1000);
    }

</script>